// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ME_SavedTeleports","status":true,"description":"You can go back to the entrance you came from","parameters":{}}
];
